## Numpy

Numpy is a python package. it stands for 'Numerical python '
it is a library consisting of multidimensional array objects and a collection of routlines for processing of array.
Numpy is one of the most important foundational package for Numerical computing in python
some of the important things in Numpy
1. ndrray - multidimesional array for fast array-oriented and broadcasting
2. operations
3. fast mathematical operations without for loops
4. reading / writing array data to the disk
5. memory mapped files
6. linear algebra, random number generation

In [ ]:
# short points
# numerical python
# scientific and mathematical calculation
# multi dimesinal array
# perfrom many operations in that array


In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([1,2,3]) # 1D array

In [ ]:
arr1

array([1, 2, 3])

## Usage for data analysis operations
1. Fast vectorized multidimentional array operation for data cleanup,subsetting,filtering and other operations
2. Sorting unique and set operations
3. Descriptive statistics,aggergating and summarizing data
4. Merging and joining hetrogenous datasets
5. Conditional logic as array experssions
6. Group-wise data manipulations

In [ ]:
arr2 = np.array([[2,3,4],[4,5,6],[7,8,9],[10,2,3]])
arr2
# 4 list = no. of rows
# 3 element = no. of column

array([[ 2,  3,  4],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10,  2,  3]])

In [ ]:
arr2.shape

(4, 3)

In [ ]:
arr3 = np.array([[1,2,3,4],[5,6,7,8]])
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr3.shape

(2, 4)

## Other ways to create new arrays
1. ones - to create an array of 1s
2. zeros - to create an array of 0s
3. empty - create array without intializing it's values
to create higher dimensional array pass the tuple as dimension of array



### 1. Zero
zero() Creates an array filled zero values.argument is an array or tuple with size of each dimension of the array

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

### 2. Ones
ones() - filled with one values

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [ ]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

### 3. Empty
empty function create an array of specified shape. argument is an array or tuple with length of each dimension of array
value created are random and empty array needs to be assigned before use

In [ ]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.empty((2,2))

array([[1., 1.],
       [1., 1.]])

In [ ]:
arrx = np.empty((3,3,3))
arrx

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

### Combining NDarray
- New ndarray can be created
vstack() and hstack are two popular methods
1. vstack() - Vertical stack
2. hstack() - Horizontal stack  

### Veritcal Stack
Two or more array can be stacked vertically

In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [ ]:
# the array we combine the dimesion should be same

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)
print('--------')
arr2 = np.array([[7,8,9],[10,11,12]])
print(arr2)
print('---------')

[[1 2 3]
 [4 5 6]]
--------
[[ 7  8  9]
 [10 11 12]]
---------


In [ ]:
arr1+arr2

array([[ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
arr3 = np.vstack((arr1,arr2))
arr3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### Horizontal stack
Two or more ndarray can be stacked horizontally

In [ ]:
arr4 = np.hstack((arr1,arr2))
arr4

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [ ]:
arr4 = np.hstack((arr2,arr1))
arr4

array([[ 7,  8,  9,  1,  2,  3],
       [10, 11, 12,  4,  5,  6]])

In [ ]:
arr0 = np.vstack((arr2,arr1))
arr0

array([[ 7,  8,  9],
       [10, 11, 12],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [ ]:
arrx = np.vstack((arr0,arr3))
arrx

array([[ 7,  8,  9],
       [10, 11, 12],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
# 3 2D matrices
arrz = np.array([[13,16,19]])
ar = np.vstack((arr1,arr2,arrz))
ar

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 16, 19]])

### Concatenating ndarray
Concatenate() take a sequence (tuple,list etc) and join them along input axis

In [ ]:
arr1 = np.array([[3,2,1],[4,5,6]])

In [ ]:
arr2 = np.array([[5,6,2],[92,1,5]])
arr2

array([[ 5,  6,  2],
       [92,  1,  5]])

In [ ]:
arr3 = np.concatenate((arr1,arr2))
arr3

array([[ 3,  2,  1],
       [ 4,  5,  6],
       [ 5,  6,  2],
       [92,  1,  5]])

In [ ]:
arr3 = np.concatenate([arr1,arr2],axis=0) # axis = 0 = vstack & 1 = hstack
print(arr3)
print(arr3.shape)

[[ 3  2  1]
 [ 4  5  6]
 [ 5  6  2]
 [92  1  5]]
(4, 3)


In [ ]:
arr3 = np.concatenate([arr1,arr2],axis=1)
print(arr3)
print(arr3.shape)

[[ 3  2  1  5  6  2]
 [ 4  5  6 92  1  5]]
(2, 6)


### Splitting Array
Divide the array into subarray along a specfied axis  

In [ ]:
# numpy.split(ary,indices_or_section,axis)

In [ ]:
a = np.arange(12)
print('First array ')
print(a)
print('\n')
print('Spltting the array in 3 equal size arrays ')
b = np.split(a,3)  # split(array,divide in eual parts)
print(b)

First array 
[ 0  1  2  3  4  5  6  7  8  9 10 11]


Spltting the array in 3 equal size arrays 
[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]


In [ ]:
a =np.arange(10)

print("\n")
c=np.split(a,[3,5,10]) # we split in unequal parts then we pass array and index in a list
print(c)
print("\n")
print("Splitting the array indicated first at 3, second at 5 and remaining in 3rd")

print("\n")
d =np.split(a,[3,5,]) # we put empty(,) for to fill all the remaining in third
print(d)



[array([0, 1, 2]), array([3, 4]), array([5, 6, 7, 8, 9]), array([], dtype=int64)]


Splitting the array indicated first at 3, second at 5 and remaining in 3rd


[array([0, 1, 2]), array([3, 4]), array([5, 6, 7, 8, 9])]


In [ ]:
a =np.arange(15)
print("Splitting the array indicated first at 3, second at 5 and remaining in 3rd")
print("\n")
c=np.split(a,[3,5,10]) # if elements are more than specified index then it will put remaining elements in empty array which is created by default
c

Splitting the array indicated first at 3, second at 5 and remaining in 3rd




[array([0, 1, 2]),
 array([3, 4]),
 array([5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14])]

In [ ]:
a =np.arange(9)
c=np.split(a,[2,3,5])
c

[array([0, 1]), array([2]), array([3, 4]), array([5, 6, 7, 8])]

In [ ]:
arr3d=np.array([[[1,2,3],[4,5,8]],[[7,8,9],[10,11,12]],[[32,33,55],[1,23,9]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  8]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[32, 33, 55],
        [ 1, 23,  9]]])

In [ ]:
arr3d[0:2,1,1]

array([ 5, 11])

In [ ]:
import numpy as np
arr3d=np.array([[[1,2,3],[4,5,8]],[[7,8,9],[10,11,12]],[[32,33,55],[1,23,9]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  8]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[32, 33, 55],
        [ 1, 23,  9]]])

In [ ]:
arr3d[0:2,1,1]

array([ 5, 11])

# data types for ndarray
def- data type or dtype cobtains the information about the type of data


In [ ]:
array1= np.array([3,4,5],dtype=int)
array1

array([3, 4, 5])

In [ ]:
array2= np.array([3.4,4.5,5.6],dtype=np.int32)
array2

array([3, 4, 5], dtype=int32)

# casting
def- you can convert or cast an array from one data type to another

In [ ]:
import numpy as np
array1 = np.array([1,2,3,4,5])

In [ ]:
array1.dtype

dtype('int64')

In [ ]:
array1.astype(np.float64)

array([1., 2., 3., 4., 5.])

if the float is casted into int,the decimal is truncated

In [ ]:
arra1=np.array([1.5,2.9,3.1,4.0])
arra1.astype(np.int32)

array([1, 2, 3, 4], dtype=int32)

you can convert a string representing numbers into number using astype

In [ ]:
arra1 = np.array(['2.3','5.6','3.55'],dtype=np.string_)

In [ ]:
arra1.dtype

dtype('S4')

In [ ]:
arra1.astype(np.float64)

array([2.3 , 5.6 , 3.55])

# Arthematic with Numpy Array
def- numpy suppory the batch opertions on data without for loops.this is called as vectorization

In [ ]:
alist=(1,2,3,4,5)
list2=(6,7,8,9,0)
alist=list2

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr**2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [ ]:
arr+arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [ ]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
arr*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [ ]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [ ]:
arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

# Comparsion of Array

In [ ]:
arr2 = np.array([[3,4,5],[6,2,8]])
arr2

array([[3, 4, 5],
       [6, 2, 8]])

In [ ]:
arr3=np.array([[57,3,2],[4,1,5]])
arr3

array([[57,  3,  2],
       [ 4,  1,  5]])

In [ ]:
arr2>arr3

array([[False,  True,  True],
       [ True,  True,  True]])

In [ ]:
arr3>arr2

array([[ True, False, False],
       [False, False, False]])

# Assign a value to a slice
# def- A scalar value can be assigned to a slice also it broadcasts to the whole slice

In [ ]:
import numpy as np

In [ ]:
arr1 = np.array ([12,13,14,15,16,17])

In [ ]:
arr1

array([12, 13, 14, 15, 16, 17])

In [ ]:
arr2=arr1

In [ ]:
arr2

array([12, 13, 14, 15, 16, 17])

In [ ]:
arr2[3:5]

array([15, 16])

# Array Reshaping
def - In machine learning and deep learning you need to reshape data as per requirement of the model

# data shape
def- shape attribute returnxs the tuple of the length of each dimension of the array

In [ ]:
arr1=np.array([11,22,33,44,55,67])
arr1.shape

(6,)

In [ ]:
arr1.reshape(2,3)

array([[11, 22, 33],
       [44, 55, 67]])

# reshape Array from 1d to 2d
 reshape-to reshape the array takes single argument to specify new shape
 if you want to reshape 1d to 2d array with 1 column you can use arr1.shape[0]for first and 1 for second dimension

In [ ]:
arr1=np.array([11,22,33,44,55])
print(arr1)
print(arr1.shape)

[11 22 33 44 55]
(5,)


In [ ]:
arr1.shape[0]


5

In [ ]:
print(arr1.reshape((arr1.shape[0],1)))
print(arr1.reshape((arr1.shape[0],1)).shape)

[[11]
 [22]
 [33]
 [44]
 [55]
 [66]
 [77]
 [88]
 [99]]
(9, 1)


In [ ]:
print(arr1.reshape(9,1))

[[11]
 [22]
 [33]
 [44]
 [55]
 [66]
 [77]
 [88]
 [99]]


In [ ]:
arr1=np.array([11,22,33,44,55,66,77,88,99])
print(arr1)
print(arr1.reshape(3,3))
arr1.reshape(3,3)

[11 22 33 44 55 66 77 88 99]
[[11 22 33]
 [44 55 66]
 [77 88 99]]


array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [ ]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)
print(arr1.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [ ]:
print(arr1.shape[1])

3


In [ ]:
arr1=arr1.reshape(arr1.shape[0],arr1.shape[1],1)
print(arr1)
print(arr1.shape)
arr1.ndim

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]
(3, 3, 1)


3

# Writting and Loadind array


In [ ]:
np.savetxt('yogesh.csv',arr0)

In [ ]:
import os
os.getcwd()

'/content'

In [ ]:
np.loadtxt('yogesh.csv')

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [ ]:
np.savetxt('arrtxt.txt',arr0)
np.loadtxt('arrtxt.txt')

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [ ]:
arr0=np.arange(10)
np.save('arrn.npy',arr0)

In [ ]:
np.load('arrn.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# flattening and ravel array


In [ ]:
arr1=np.array([[12,33,40],[33,44,55]])

In [ ]:
arr1

array([[12, 33, 40],
       [33, 44, 55]])

In [ ]:
arr1.ndim

2

In [ ]:
a=arr1.ravel()  # it change the original array
a.ndim
a

array([12, 33, 40, 33, 44, 55])

In [ ]:
a[2:4]=66
a

array([12, 33, 66, 66, 44, 55])

In [ ]:
arr1

array([[12, 33, 66],
       [66, 44, 55]])

In [ ]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
b=arr2.flatten()  #it did not change origninal array
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b[2:5]=20
b

array([ 1,  2, 20, 20, 20,  6,  7,  8,  9])

In [ ]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Array broadcasting
# Array Arthmetic Limitation
Array with different shape and size cannot be added or subtrcate in arthmetic<br>
A one dimension array with length 8 can be added or subtracted from another array of lenght 8 only.

This Limittion in Arithmetic is limiting
python has builitin functionlity ** broadcasting ** to address this

# Broadcasting
Broadcasting solves the problem of different shape by relicating the smaller array along the last mismatched diminsion

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
b = 2
print(b)
c = a + b
print(c)

[[1 2 3]
 [4 5 6]]
2
[[3 4 5]
 [6 7 8]]


In [ ]:
a = np.array([1,2,3])
print(a)
b = 2
print(b)
c = a + b
print(c)

[1 2 3]
2
[3 4 5]


# 1D and 2D Array Broadcasting

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
b = np.array([7,8,6])
print(b)
c = a + b # 1D array is broadcasting across each row of 2D by creating a copy of itself
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[7 8 6]
[[ 8 10  9]
 [11 13 12]
 [14 16 15]]


#pandas Data Struture
series
one dimensional array like obect contains
1. sequence of values
2. associated array of indexes shows vaalues on the left and vales on the right

In [ ]:
import pandas as pd
series1=pd.Series([2,1,2])
print(series1)

0    2
1    1
2    2
dtype: int64


In [ ]:
series1

0    2
1    1
2    2
dtype: int64

In [ ]:
series1.values

array([2, 1, 2])

In [ ]:
series1.index

RangeIndex(start=0, stop=3, step=1)

In [ ]:
import pandas as pd
obj2= pd .Series([400,379,389],index=[10,20,20])
print(obj2)

10    400
20    379
20    389
dtype: int64


In [ ]:
obj2[20].sum()

768

In [ ]:
obj2*2

10    800
20    758
20    778
dtype: int64

In [ ]:
obj2+2

10    402
20    381
20    391
dtype: int64

In [ ]:
obj2-2

10    398
20    377
20    387
dtype: int64

In [ ]:
import numpy as np
np.exp(obj2)

10    5.221470e+173
20    3.959211e+164
20    8.720742e+168
dtype: float64

In [ ]:
'M'in obj2 # can be treated like ordered dict

False

Series can be created from python dict

In [ ]:
dict1= {'local':[32000,2000],
        'temp':200,
        'root':1000}
series=pd.Series(dict1)
series
# dict=>series 1 key : 1 value
# key = index
# value = value

local    [32000, 2000]
temp               200
root              1000
dtype: object

In [ ]:
dict2={'student':['riya','manish','amit','raju'],
       'student_id':[101,102,103,104],
       'Branch':['cs','IT','Mech','Elct']}
dict2

# key = columns
# values = column data

{'student': ['riya', 'manish', 'amit', 'raju'],
 'student_id': [101, 102, 103, 104],
 'Branch': ['cs', 'IT', 'Mech', 'Elct']}

In [ ]:
df=pd.DataFrame(dict2)    # DataFrame "DF" should be captail
df

student  student_id Branch
0    riya         101     cs
1  manish         102     IT
2    amit         103   Mech
3    raju         104   Elct

In [ ]:
series=pd.Series(dict2)
series

student       [riya, manish, amit, raju]
student_id          [101, 102, 103, 104]
Branch              [cs, IT, Mech, Elct]
dtype: object

In [ ]:
dictdata={'Mumbai':[35000,2200],
          'Delhi':[45000,3300],
          'Chennai':[2200,34000],
          'Kolkate':[29000,1000]}

In [ ]:
obj3=pd.Series(dictdata)


In [ ]:
df1=pd.DataFrame(dictdata)
df1

Mumbai  Delhi  Chennai  Kolkate
0   35000  45000     2200    29000
1    2200   3300    34000     1000

you can change the key index by passing dict keys

In [ ]:
dictdata={'Mumbai':[35000,2000],
          'Delhi':[45000,3000],
          'Chennai':[2200,34000],
          'kolkata0':[29000,1000],}
cities=['Mumbai','Chennai','Pune','Delhi','Bhopal']
obj4=pd.Series(dictdata,index=cities)
obj4

Mumbai     [35000, 2000]
Chennai    [2200, 34000]
Pune                 NaN
Delhi      [45000, 3000]
Bhopal               NaN
dtype: object

In [ ]:
df=pd.DataFrame(dictdata,index=[2,3])
df

Mumbai  Delhi  Chennai  kolkata0
2   35000  45000     2200     29000
3    2000   3000    34000      1000

In [ ]:
pd.isnull(obj4)

Mumbai     False
Chennai    False
Pune        True
Delhi      False
Bhopal      True
dtype: bool

In [ ]:
pd.isnull(obj4).sum()

2

In [ ]:
pd.notnull(obj4)

Mumbai      True
Chennai     True
Pune       False
Delhi       True
Bhopal     False
dtype: bool

In [ ]:
pd.notnull(obj4).sum()

3

# DataFrame
DataFrame - a rectangular table of data
it has an ordered collection of columns
Each columns can be a different value (numeric,string,bollean,etc)
The DataFrame has both a row and column index
the data is stored as one or more two dimensional blocks rather than a list,dict,or some other collection of one dimensional

In [ ]:
import pandas as pd
data={'state':['ohio','ohio','ohio','Nevada','Nevada','Nevada'],
      'year':[2000,2001,2002,2003,2000,2001,2002],
      'pop':[1.5,1.6,2.5,3.9,4.1,6.7]}
frame = pd.DataFrame(data)
frame

ValueError: All arrays must be of the same length

In [ ]:
frame=pd.DataFrame(data)
frame

ValueError: All arrays must be of the same length

In [ ]:
frame.rename(columns={'state':'city','year':'year1','pop':'pop1'},inplace=True)
frame

In [ ]:
# p=[2,3,4,5,6,7]
#syntax to add the column
frame['aman']=[2,3,4,5,6,7]

In [ ]:
frame

In [ ]:
frame[['year1','pop1','city']]

In [ ]:
# column = data change
# how to add column
p=[1,2,3,45,6,7,]
frame['pop1']=p
frame

{'state': ['ohio', 'ohio', 'ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2003, 2000, 2001, 2002],
 'pop': [1.5, 1.6, 2.5, 3.9, 4.1, 6.7],
 'aman': [2, 3, 4, 5, 6, 7],
 'pop1': [1, 2, 3, 45, 6, 7]}

In [ ]:
frame.head()   # top 5 rows

AttributeError: 'dict' object has no attribute 'head'

In [ ]:
frame.tail()    #bottom 5 rows

AttributeError: 'dict' object has no attribute 'tail'

In [ ]:
frame.sample()  # it returns randomly rows

AttributeError: 'dict' object has no attribute 'sample'

In [ ]:
frame=pd.DataFrame(frame,columns=['year1','aman','pop1','city'])
# you can specify the sequence of columns

In [ ]:
#data=dict
df=pd.DataFrame()

In [ ]:
l1=[1,2,3,4,5]
# resultant output
# L1=[1,4.3.16,5]

In [ ]:
l1=[x**2 if x%2==0 else x for x in l]
l1

[1, 4, 3, 16, 5]

In [ ]:
l1=[]
for x in l:
  if x%2==0:
    l1.append(x**2)
  else:
    l1.append(x)

#Nested Dict of Dicts
def- outr dict key as column and nested dicgt as key

In [ ]:
import pandas as pd

In [ ]:
pop= {'Nevada':{2001:2.4, 2002:5.6, 2000:2},
      'Ohio':{2000:4.5, 2001:3.4, 2002:6.7}}

In [ ]:
pop

{'Nevada': {2001: 2.4, 2002: 5.6, 2000: 2},
 'Ohio': {2000: 4.5, 2001: 3.4, 2002: 6.7}}

In [ ]:
frame3= pd.DataFrame(pop)
frame3

Nevada  Ohio
2001     2.4   3.4
2002     5.6   6.7
2000     2.0   4.5

In [ ]:
frame3.values

array([[2.4, 3.4],
       [5.6, 6.7],
       [2. , 4.5]])

In [ ]:
frame3.T   #transpose

2001  2002  2000
Nevada   2.4   5.6   2.0
Ohio     3.4   6.7   4.5

In [ ]:
frame3.index.name='year'
frame3.columns.name='state'
frame3

state  Nevada  Ohio
year               
2001      2.4   3.4
2002      5.6   6.7
2000      2.0   4.5

In [ ]:
frame3[2002,'Nevada']=2

In [ ]:
frame3.loc[2002,'Nevada']=2
frame3

state  Nevada  Ohio  (2002, Nevada)
year                               
2001      2.4   3.4               2
2002      2.0   6.7               2
2000      2.0   4.5               2

In [ ]:
#Index Objects

In [ ]:
Any array or sequence of labels while contructing the Series or DataFrame is internally converted into index

SyntaxError: invalid syntax (<ipython-input-2-ce1014691e5b>, line 1)

In [ ]:
import pandas as pd

obj = pd.Series(range(3), index=['a','b','c'])
obj

a    0
b    1
c    2
dtype: int64

In [ ]:
index = obj.index

In [ ]:
index[1:] # index actual index

Index(['b', 'c'], dtype='object')

In [ ]:
# index are immmutable cannot be modified

# Rendixing
reindex - create a new object with the data conformed to a new index

In [ ]:
import pandas as pd
obj2 = pd.Series([4.5,6.7,7.8,-5.8], index=['d','a','c','b'])
obj2

d    4.5
a    6.7
c    7.8
b   -5.8
dtype: float64

In [ ]:
obj2= obj2.reindex(['a','b','c','d','e'])
obj2

a    6.7
b   -5.8
c    7.8
d    4.5
e    NaN
dtype: float64

In [ ]:
obj3=pd.Series(['blue','red','yellow'],index=[0,2,4])
obj3

0      blue
2       red
4    yellow
dtype: object

In [ ]:
obj3.reindex(range(10))

0      blue
1       NaN
2       red
3       NaN
4    yellow
5       NaN
6       NaN
7       NaN
8       NaN
9       NaN
dtype: object

In [ ]:
import numpy as np
import pandas as pd
frame2 = pd.DataFrame(np.arange(12).reshape(3,4),
                     index=['a','b','c'],
                     columns=['Ohio','Taxas','Califorina','India'])
frame2

Ohio  Taxas  Califorina  India
a     0      1           2      3
b     4      5           6      7
c     8      9          10     11

In [ ]:
frame2= frame2.reindex(['a','b','c','d','e'])
frame2

Ohio  Taxas  Califorina  India
a   0.0    1.0         2.0    3.0
b   4.0    5.0         6.0    7.0
c   8.0    9.0        10.0   11.0
d   NaN    NaN         NaN    NaN
e   NaN    NaN         NaN    NaN

In [ ]:
frame1= pd.DataFrame(np.arange(9).reshape(3,3),
                    index=['a','b','c'],
                    columns=['Obio','Texas','California'])
frame1

Obio  Texas  California
a     0      1           2
b     3      4           5
c     6      7           8

In [ ]:
frame1=frame1.reindex(['a','b','c','d','e'])
frame1

Obio  Texas  California
a   0.0    1.0         2.0
b   3.0    4.0         5.0
c   6.0    7.0         8.0
d   NaN    NaN         NaN
e   NaN    NaN         NaN

In [ ]:
frame1+frame2

#Dropping Enteries
drop- use drop to return object with dropping values

In [ ]:
n_obj= pd.Series(['a','b','c','d','e'])
n_obj

0    a
1    b
2    c
3    d
4    e
dtype: object

In [ ]:
n_obj=obj.drop('c')
n_obj

AttributeError: 'list' object has no attribute 'drop'

In [ ]:
obj.drop(['a','b','c'])

AttributeError: 'list' object has no attribute 'drop'

In [ ]:
data = pd.DataFrame(np.arange(16).reshape(4,4),
                    index=['Ohio','Texas','Califorina','Nevada'],
                    columns=['one','two','three','four'])
data

one  two  three  four
Ohio          0    1      2     3
Texas         4    5      6     7
Califorina    8    9     10    11
Nevada       12   13     14    15

In [ ]:
data.drop(['Ohio','Nevada'],axis=0)   # drop the rows

one  two  three  four
Texas         4    5      6     7
Califorina    8    9     10    11

In [ ]:
# data.drop(['two','four'],axis=0)

In [ ]:
import pandas as pd
frame=pd.DataFrame(np.arange(9).reshape(3,3),
                 index=['a','c','d'],
                 columns=['obio','texas','cali'])
frame

obio  texas  cali
a     0      1     2
c     3      4     5
d     6      7     8

In [ ]:
obj['a':'d']

Empty DataFrame
Columns: [obio, texas, cali]
Index: []

In [ ]:
obj

obio  texas  cali
d     0      1     2
a     3      4     5
b     6      7     8

In [ ]:
obj['a':'d']=[1,2,3]
obj

obio  texas  cali
d     0      1     2
a     3      4     5
b     6      7     8

In [ ]:
frame1

Obio  Texas  California
a   0.0    1.0         2.0
b   3.0    4.0         5.0
c   6.0    7.0         8.0
d   NaN    NaN         NaN
e   NaN    NaN         NaN

In [ ]:
frame1['Obio']

a    0.0
b    3.0
c    6.0
d    NaN
e    NaN
Name: Obio, dtype: float64

In [ ]:
frame1['Texas']>4

a    False
b    False
c     True
d    False
e    False
Name: Texas, dtype: bool

In [ ]:
frame1[frame1['Texas']>3]

Obio  Texas  California
b   3.0    4.0         5.0
c   6.0    7.0         8.0

In [ ]:
df1= pd.DataFrame(np.arange(9).reshape(3,3),
                  columns=list('bcd'),
                  index=['obio','texas','cali'])
print(df1)
df2= pd.DataFrame(np.arange(12).reshape(4,3),
                  columns=list('bde'),
                  index=['utah','obio','texas','orange'])
print(df2)

       b  c  d
obio   0  1  2
texas  3  4  5
cali   6  7  8
        b   d   e
utah    0   1   2
obio    3   4   5
texas   6   7   8
orange  9  10  11


In [ ]:
df1

b  c  d
obio   0  1  2
texas  3  4  5
cali   6  7  8

In [ ]:
df2

b   d   e
utah    0   1   2
obio    3   4   5
texas   6   7   8
orange  9  10  11

In [ ]:
df1.add(df2,fill_value=0)

b    c     d     e
cali    6.0  7.0   8.0   NaN
obio    3.0  1.0   6.0   5.0
orange  9.0  NaN  10.0  11.0
texas   9.0  4.0  12.0   8.0
utah    0.0  NaN   1.0   2.0

#Operation Between DataFrame and Series

In [ ]:
import pandas as pd
import numpy as np
frame=pd.DataFrame(np.arange(12).reshape((4,3)),
                   columns=list('bde'),
                   index=['utah','ohio','texas','orange'])
series=frame.iloc[0]
frame

b   d   e
utah    0   1   2
ohio    3   4   5
texas   6   7   8
orange  9  10  11

In [ ]:
series=frame.iloc[0]
series

b    0
d    1
e    2
Name: utah, dtype: int64

In [ ]:
frame-series  # check Broadcasting

b  d  e
utah    0  0  0
ohio    3  3  3
texas   6  6  6
orange  9  9  9

# sorting
uses sort_index and sort_value

In [ ]:
obj= pd.Series(range(4),index=['d','a','b','c'])
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [ ]:
obj=pd.Series([4,7,-3,2])
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [ ]:
obj=pd.Series([4,np.nan, 7,np.nan, -3, 2])#missing values in end
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [ ]:
frame=pd.DataFrame(np.arange(12).reshape((4,3)),
                   columns=list('bde'),
                   index=['utah','ohio','texas','orange'])
frame

b   d   e
utah    0   1   2
ohio    3   4   5
texas   6   7   8
orange  9  10  11

In [ ]:
frame.sort_index() #sorting on index

b   d   e
ohio    3   4   5
orange  9  10  11
texas   6   7   8
utah    0   1   2

In [ ]:
frame.sort_index(axis=1)#sorting on column

b   d   e
utah    0   1   2
ohio    3   4   5
texas   6   7   8
orange  9  10  11

In [ ]:
frame.sort_index(axis=0,ascending=False) #Ascending/Descending order

b   d   e
utah    0   1   2
texas   6   7   8
orange  9  10  11
ohio    3   4   5

In [ ]:
frame=pd.DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [ ]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [ ]:
frame.sort_values(by=['a','b']) #use multiple column

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

# Loading Data
use read_csv read_table

In [2]:
import os
os.getcwd()

'c:\\Users\\ACER\\OneDrive\\Desktop\\seven mentors python'

In [3]:
df= pd.read_excel('C:\Users\ACER\Downloads\Column Operations.xlsx')
df

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (3848605204.py, line 1)

In [ ]:
df.head() #top 5 rows

NameError: name 'df' is not defined

In [ ]:
df.tail(7) #bottom 5 rows

NameError: name 'df' is not defined

In [ ]:
df.sample()  # it shows the rows randomly

NameError: name 'df' is not defined

In [ ]:
df.info()

NameError: name 'df' is not defined

In [ ]:
df.describe() #it gives seven number

NameError: name 'df' is not defined

In [ ]:
df.isnull().sum()

NameError: name 'df' is not defined

In [ ]:
df.shape

NameError: name 'df' is not defined